### ISSUE TITLE
Does it work with keycloak 9.0.0?

### ISSUE THREAD

**Issue by bilak** [httpsOmkar/carbon-keycloak-theme#3]
Hi, 
I'm trying to include this theme in keycloak 9.0.0 docker, but it seems to be not working. 
Maybe I did something wrong?

Steps:
* yarn package inside project
* mount `./carbon:/opt/jboss/keycloak/themes/carbon`
* start container
* choose carbon in keycloak themes

<img width="1680" alt="carbontheme" src="https://user-images.githubusercontent.com/5826062/76712051-713cb700-6715-11ea-8b68-f5b0b52f6fab.png">

**Comment by 0xHexE** [comment]
Currently I dont support this for keycloak admin this theme is available only for login and the my account page

**Comment by 0xHexE** [comment]
and before starting the container did you run yarn build
